"""initial

Revision ID: 7a3092a73045
Revises: 
Create Date: 2024-01-08 11:13:29.654044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3092a73045'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paydetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('punches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('punch_date', sa.Date(), nullable=False),
    sa.Column('punch_in', sa.Time(), nullable=False),
    sa.Column('punch_out', sa.Time(), nullable=True),
    sa.Column('hours_worked', sa.Interval(), server_default='0 seconds', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('punch_date', 'punch_in', 'punch_out', name='punches_compound_key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pay_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pay_id'], ['paydetails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employeedetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('badge_number', sa.Integer(), nullable=False),
    sa.Column('hire_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timecards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timecard_punches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timecard_id', sa.Integer(), nullable=True),
    sa.Column('punch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['punch_id'], ['punches.id'], ),
    sa.ForeignKeyConstraint(['timecard_id'], ['timecards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timecard_punches')
    op.drop_table('timecards')
    op.drop_table('employeedetails')
    op.drop_table('departments')
    op.drop_table('users')
    op.drop_table('punches')
    op.drop_table('paydetails')
    # ### end Alembic commands ###
